package com.spd.hmsas;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * hmsasService service = new hmsasService();
 * HmsasserverPortType portType = service.getHmsasserverPort();
 * portType.getAwsqcdataToarray(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "hmsasService", targetNamespace = "urn:hmsas", wsdlLocation = "http://172.24.176.29/hmsas/wsdl/hmsas.wsdl")
public class HmsasService extends Service {

	private final static URL HMSASSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.spd.hmsas.HmsasService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.spd.hmsas.HmsasService.class.getResource(".");
			url = new URL(baseUrl, "http://172.24.176.29/hmsas/wsdl/hmsas.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://172.24.176.29/hmsas/wsdl/hmsas.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HMSASSERVICE_WSDL_LOCATION = url;
	}

	public HmsasService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HmsasService() {
		super(HMSASSERVICE_WSDL_LOCATION,
				new QName("urn:hmsas", "hmsasService"));
	}

	/**
	 * 
	 * @return returns HmsasserverPortType
	 */
	@WebEndpoint(name = "hmsasserverPort")
	public HmsasserverPortType getHmsasserverPort() {
		return super.getPort(new QName("urn:hmsas", "hmsasserverPort"),
				HmsasserverPortType.class);
	}

}
